import mongoose from 'mongoose';

const licenseRequestSchema = new mongoose.Schema({
    businessId: {
        type: mongoose.Schema.Types.ObjectId,
        ref: 'User',
        required: true
    },
    walletAddress: {
        type: String,
        required: true
    },
    businessName: {
        type: String,
        required: true
    },
    licenseType: {
        type: String,
        required: true
    },
    licenseId: {
        type: String,
        default: '' // Optional, provided by Business or generated by Regulator
    },
    documentHash: {
        type: String,
        required: true
    },
    status: {
        type: String,
        enum: ['pending', 'approved', 'rejected'],
        default: 'pending'
    },
    createdAt: {
        type: Date,
        default: Date.now
    }
});

export const LicenseRequest = mongoose.model('LicenseRequest', licenseRequestSchema);
